version: '2'

services:

  php:

    image: hamdaniphp

    ports:

      - "80:80"

      - "443:443"

    volumes:

      - ./app:/var/www/html

    links:

      - db



  db:

    image: puspamysql

    volumes:

     - ./db:/var/lib/mysql

    environment:

     - MYSQL_ROOT_PASSWORD=repi